const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const PORT = process.env.PORT || 3000;
const ROOT = __dirname, PUBLIC = path.join(ROOT, 'public'), DB_FILE = path.join(ROOT, 'data.json');

const demoBooks = [
  ['Physics Part I — Class 12','H.C. Verma','Class 12','Physics','NCERT','Excellent',420,2,'A well-kept foundation text with clear concepts and worked examples.'],
  ['Organic Chemistry','Morrison & Boyd','Class 12','Chemistry','Reference Books','Good',360,1,'Comprehensive organic chemistry reference, lightly annotated in pencil.'],
  ['Mathematics for JEE','Cengage Learning','JEE','Mathematics','Exam Prep','Like New',650,3,'Complete JEE preparation volume with practice problems.'],
  ['Biology — NEET Guide','Trueman','NEET','Biology','Exam Prep','Good',490,2,'High-yield NEET guide; all chapters included.'],
  ['Computer Science with Python','Sumita Arora','Class 12','Computer Science','School Books','Excellent',280,4,'CBSE-aligned text with programs and theory.'],
  ['Engineering Mathematics','B.S. Grewal','Engineering','Mathematics','College Books','Good',390,2,'A reliable first-year engineering mathematics companion.']
];
function initial(){ const seller={id:'seller-demo',name:'Aarav Sharma',email:'seller@educycle.demo',modes:['buyer','seller'],verified:true,password:hash('demo123'),createdAt:Date.now()}; return {users:[seller],books:demoBooks.map((b,i)=>({id:'book-'+(i+1),sellerId:seller.id,title:b[0],author:b[1],classGrade:b[2],subject:b[3],category:b[4],condition:b[5],price:b[6],quantity:b[7],description:b[8],publisher:'Academic Press',edition:'2024 Edition',board:'CBSE',image:`https://images.unsplash.com/photo-${['1544947950-fa07a98d237f','1512820790803-83ca734da794','1495446815901-a7297e633e8d','1532012197267-da84d127e765','1543002588-bfa74002ed7e','1511108690759-009324a90311'][i]}?auto=format&fit=crop&w=700&q=80`,status:'active',createdAt:Date.now()-i*86400000})),carts:{},orders:[],sessions:{}}; }
function hash(s){return crypto.createHash('sha256').update(s).digest('hex')}
function load(){if(!fs.existsSync(DB_FILE)){const d=initial(); save(d); return d} try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{return initial()}}
function save(d){fs.writeFileSync(DB_FILE,JSON.stringify(d,null,2))}
let db=load();
function respond(res,status,body){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{reject(new Error('Invalid request'))}})})}
function user(req){const token=(req.headers.authorization||'').replace('Bearer ','');return token&&db.sessions[token]?db.users.find(u=>u.id===db.sessions[token]):null}
function auth(req,res){const u=user(req);if(!u)return respond(res,401,{error:'Please log in to continue.'});return u}
function bookView(b){const s=db.users.find(u=>u.id===b.sellerId);return {...b,seller:{name:s?.name||'Student seller',listings:db.books.filter(x=>x.sellerId===b.sellerId).length}}}
function id(prefix){return prefix+'-'+crypto.randomBytes(7).toString('hex')}
function orderView(o){return {...o,buyer:db.users.find(u=>u.id===o.buyerId)?.name,items:o.items.map(i=>({...i,book:bookView(db.books.find(b=>b.id===i.bookId)||{title:i.title,sellerId:i.sellerId})}))}}
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://x'), p=url.pathname, method=req.method;
 if(p.startsWith('/api/')){
  if(p==='/api/health')return respond(res,200,{ok:true});
  if(p==='/api/auth/signup'&&method==='POST'){const x=await body(req);if(!x.name||!x.email||!x.password)return respond(res,400,{error:'Please complete all fields.'});if(db.users.some(u=>u.email.toLowerCase()===x.email.toLowerCase()))return respond(res,409,{error:'An account with this email already exists.'});const u={id:id('user'),name:x.name.trim(),email:x.email.toLowerCase(),modes:['buyer','seller'],verified:false,password:hash(x.password),createdAt:Date.now()};db.users.push(u);const t=id('session');db.sessions[t]=u.id;save(db);return respond(res,201,{token:t,user:{id:u.id,name:u.name,email:u.email,modes:u.modes||['buyer','seller'],verified:!!u.verified}})}
  if(p==='/api/auth/login'&&method==='POST'){const x=await body(req),u=db.users.find(u=>u.email===String(x.email).toLowerCase()&&u.password===hash(x.password||''));if(!u)return respond(res,401,{error:'Invalid email or password.'});const t=id('session');db.sessions[t]=u.id;save(db);return respond(res,200,{token:t,user:{id:u.id,name:u.name,email:u.email,modes:u.modes||['buyer','seller'],verified:!!u.verified}})}
  if(p==='/api/auth/logout'&&method==='POST'){const t=(req.headers.authorization||'').replace('Bearer ','');delete db.sessions[t];save(db);return respond(res,200,{ok:true})}
  if(p==='/api/me'){const u=auth(req,res);if(!u)return;return respond(res,200,{id:u.id,name:u.name,email:u.email,modes:u.modes||['buyer','seller'],verified:!!u.verified})}
  if(p==='/api/books'&&method==='GET'){let books=db.books.filter(b=>b.status==='active');const q=(url.searchParams.get('q')||'').toLowerCase();for(const k of ['subject','classGrade','category','condition']){const v=url.searchParams.get(k);if(v)books=books.filter(b=>b[k]===v)}if(q)books=books.filter(b=>[b.title,b.author,b.subject,b.publisher].join(' ').toLowerCase().includes(q));const max=Number(url.searchParams.get('max')||999999),min=Number(url.searchParams.get('min')||0);books=books.filter(b=>b.price>=min&&b.price<=max);const sort=url.searchParams.get('sort');if(sort==='low')books.sort((a,b)=>a.price-b.price);if(sort==='high')books.sort((a,b)=>b.price-a.price);if(sort==='new')books.sort((a,b)=>b.createdAt-a.createdAt);return respond(res,200,books.map(bookView))}
  if(p==='/api/books'&&method==='POST'){const u=auth(req,res);if(!u)return;const x=await body(req);for(const k of ['title','author','classGrade','subject','category','condition','price','quantity'])if(x[k]===undefined||x[k]==='')return respond(res,400,{error:'Please complete all required book details.'});if(!Number.isFinite(+x.price)||+x.price<0||!Number.isInteger(+x.quantity)||+x.quantity<0)return respond(res,400,{error:'Price and quantity must be valid positive values.'});const b={id:id('book'),sellerId:u.id,title:x.title,author:x.author,publisher:x.publisher||'',edition:x.edition||'',classGrade:x.classGrade,subject:x.subject,category:x.category,board:x.board||'',condition:x.condition,description:x.description||'',price:+x.price,quantity:+x.quantity,image:x.image||'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=700&q=80',status:'active',createdAt:Date.now()};db.books.push(b);save(db);return respond(res,201,bookView(b))}
  const match=p.match(/^\/api\/books\/([^/]+)$/);if(match){const b=db.books.find(b=>b.id===match[1]);if(!b)return respond(res,404,{error:'Book not found.'});if(method==='GET'){if(b.status!=='active'&&(!user(req)||user(req).id!==b.sellerId))return respond(res,404,{error:'Book not found.'});return respond(res,200,bookView(b))}const u=auth(req,res);if(!u)return;if(b.sellerId!==u.id)return respond(res,403,{error:'You can only manage your own listings.'});if(method==='DELETE'){b.status='deleted';save(db);return respond(res,200,{ok:true})}if(method==='PATCH'){const x=await body(req);for(const k of ['title','author','price','quantity','condition','status','description'])if(x[k]!==undefined)b[k]=k==='price'?+x[k]:k==='quantity'?+x[k]:x[k];if(b.price<0||b.quantity<0)return respond(res,400,{error:'Invalid inventory values.'});save(db);return respond(res,200,bookView(b))}}
  if(p==='/api/seller/books'){const u=auth(req,res);if(!u)return;return respond(res,200,db.books.filter(b=>b.sellerId===u.id&&b.status!=='deleted').map(bookView))}
  if(p==='/api/cart'&&method==='GET'){const u=auth(req,res);if(!u)return;const c=db.carts[u.id]||[];return respond(res,200,c.map(i=>({...i,book:bookView(db.books.find(b=>b.id===i.bookId))}))) }
  if(p==='/api/cart'&&method==='POST'){const u=auth(req,res);if(!u)return;const x=await body(req),b=db.books.find(b=>b.id===x.bookId&&b.status==='active');if(!b||b.quantity<1)return respond(res,400,{error:'This book is out of stock.'});const c=db.carts[u.id]||(db.carts[u.id]=[]),i=c.find(i=>i.bookId===b.id);if(i)i.quantity=Math.min(i.quantity+1,b.quantity);else c.push({bookId:b.id,quantity:1});save(db);return respond(res,201,{ok:true})}
  const cm=p.match(/^\/api\/cart\/([^/]+)$/);if(cm){const u=auth(req,res);if(!u)return;let c=db.carts[u.id]||[];if(method==='DELETE'){db.carts[u.id]=c.filter(i=>i.bookId!==cm[1]);save(db);return respond(res,200,{ok:true})}if(method==='PATCH'){const i=c.find(i=>i.bookId===cm[1]),b=db.books.find(b=>b.id===cm[1]),x=await body(req);if(!i||!b)return respond(res,404,{error:'Cart item not found.'});if(!Number.isInteger(+x.quantity)||+x.quantity<1||+x.quantity>b.quantity)return respond(res,400,{error:'Requested quantity is not available.'});i.quantity=+x.quantity;save(db);return respond(res,200,{ok:true})}}
  if(p==='/api/checkout'&&method==='POST'){const u=auth(req,res);if(!u)return;const c=db.carts[u.id]||[];if(!c.length)return respond(res,400,{error:'Your cart is empty.'});const items=[];for(const i of c){const b=db.books.find(b=>b.id===i.bookId);if(!b||b.status!=='active'||b.quantity<i.quantity)return respond(res,400,{error:`${b?.title||'A book'} is no longer available in that quantity.`});items.push({bookId:b.id,sellerId:b.sellerId,title:b.title,quantity:i.quantity,priceAtPurchase:b.price})}for(const i of items){db.books.find(b=>b.id===i.bookId).quantity-=i.quantity}const o={id:id('order'),buyerId:u.id,items,totalAmount:items.reduce((s,i)=>s+i.priceAtPurchase*i.quantity,0),status:'Pending',createdAt:Date.now()};db.orders.push(o);db.carts[u.id]=[];save(db);return respond(res,201,orderView(o))}
  if(p==='/api/orders'){const u=auth(req,res);if(!u)return;return respond(res,200,db.orders.filter(o=>o.buyerId===u.id).map(orderView))}
  if(p==='/api/seller/orders'){const u=auth(req,res);if(!u)return;return respond(res,200,db.orders.filter(o=>o.items.some(i=>i.sellerId===u.id)).map(o=>({...orderView(o),items:o.items.filter(i=>i.sellerId===u.id)})))}
  const om=p.match(/^\/api\/seller\/orders\/([^/]+)$/);if(om&&method==='PATCH'){const u=auth(req,res);if(!u)return;const o=db.orders.find(o=>o.id===om[1]);if(!o||!o.items.some(i=>i.sellerId===u.id))return respond(res,403,{error:'You cannot update this order.'});const x=await body(req);if(!['Pending','Confirmed','Ready','Completed','Cancelled'].includes(x.status))return respond(res,400,{error:'Invalid order status.'});o.status=x.status;save(db);return respond(res,200,orderView(o))}
  if(p==='/api/seller/stats'){const u=auth(req,res);if(!u)return;const books=db.books.filter(b=>b.sellerId===u.id&&b.status!=='deleted'),orders=db.orders.filter(o=>o.items.some(i=>i.sellerId===u.id)),items=orders.flatMap(o=>o.items.filter(i=>i.sellerId===u.id));return respond(res,200,{total:books.length,active:books.filter(b=>b.status==='active').length,sold:items.reduce((s,i)=>s+i.quantity,0),pending:orders.filter(o=>o.status==='Pending').length,completed:orders.filter(o=>o.status==='Completed').length,sales:items.reduce((s,i)=>s+i.priceAtPurchase*i.quantity,0)})}
  return respond(res,404,{error:'Not found'});
 }
 let f=p==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,p);if(!f.startsWith(PUBLIC))return respond(res,403,{error:'Forbidden'});if(!fs.existsSync(f))f=path.join(PUBLIC,'index.html');const ext=path.extname(f),types={'.html':'text/html','.css':'text/css','.js':'text/javascript'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res);
}catch(e){console.error(e);respond(res,500,{error:'Something went wrong. Please try again.'})}});
server.listen(PORT,()=>console.log(`EduCycle running at http://localhost:${PORT}`));
